services:
  historial-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quetxaltv-historial-service
    env_file:
      - .env
    ports:
      - "50055:50054"
    restart: unless-stopped
