input {
  beats {
    port => 5044
  }

  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [container] and [container][name] {
    mutate {
      add_field => { "service_name" => "%{[container][name]}" }
    }
  }

  if [message] =~ /^\s*\{/ {
    json {
      source => "message"
      target => "app_log"
      skip_on_invalid_json => true
    }
  }

  mutate {
    add_field => { "project" => "quetxal-tv" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "quetxal-tv-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}