apiVersion: v1
kind: Secret
metadata:
  name: quetxal-tv-secrets
  namespace: quetxal-tv-prod
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME"
  JWT_ACCESS_SECRET: "CHANGE_ME"
  JWT_REFRESH_SECRET: "CHANGE_ME"
  AUTH_DB_HOST: "10.10.0.2"
  AUTH_DB_PORT: "5432"
  AUTH_DB_USER: "quetxal"
  AUTH_DB_PASSWORD: "CHANGE_ME"
  AUTH_DB_NAME: "auth_db"
  AUTH_DB_SCHEMA: "auth"
  SUBSCRIPTION_DB_HOST: "10.10.0.2"
  SUBSCRIPTION_DB_PORT: "5433"
  SUBSCRIPTION_DB_USER: "quetxal"
  SUBSCRIPTION_DB_PASSWORD: "CHANGE_ME"
  SUBSCRIPTION_DB_NAME: "subscription_db"
  SUBSCRIPTION_DB_SCHEMA: "subscription"
  CATALOGO_DB_HOST: "10.10.0.2"
  CATALOGO_DB_PORT: "5434"
  CATALOGO_DB_USER: "quetxal"
  CATALOGO_DB_PASSWORD: "CHANGE_ME"
  CATALOGO_DB_NAME: "catalogo_db"
  CATALOGO_DB_SCHEMA: "catalog"
  FX_DB_HOST: "10.10.0.2"
  FX_DB_PORT: "5435"
  FX_DB_USER: "quetxal"
  FX_DB_PASSWORD: "CHANGE_ME"
  FX_DB_NAME: "fx_db"
  FX_DB_SCHEMA: "fx"
  NOTIFICATION_DB_HOST: "10.10.0.2"
  NOTIFICATION_DB_PORT: "5436"
  NOTIFICATION_DB_USER: "quetxal"
  NOTIFICATION_DB_PASSWORD: "CHANGE_ME"
  NOTIFICATION_DB_NAME: "notification_db"
  NOTIFICATION_DB_SCHEMA: "notification"
  HISTORIAL_DB_HOST: "10.10.0.2"
  HISTORIAL_DB_PORT: "5437"
  HISTORIAL_DB_USER: "quetxal"
  HISTORIAL_DB_PASSWORD: "CHANGE_ME"
  HISTORIAL_DB_NAME: "historial_db"
  HISTORIAL_DB_SCHEMA: "playback"
  GCS_BUCKET_NAME: "quetxal-tv-videos"
  GCS_SERVICE_ACCOUNT_EMAIL: "quetxal-tv-cicd@quetxal-tv-g8.iam.gserviceaccount.com"
  SMTP_USER: "CHANGE_ME"
  SMTP_PASSWORD: "CHANGE_ME"
  SMTP_FROM: "CHANGE_ME"
  EXCHANGE_API_KEY: "CHANGE_ME"
