# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc import fx_pb2 as fx__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fx_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FxServiceStub:
    """─── Servicio FX ────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetExchangeRate = channel.unary_unary(
                '/fx.FxService/GetExchangeRate',
                request_serializer=fx__pb2.ExchangeRateRequest.SerializeToString,
                response_deserializer=fx__pb2.ExchangeRateResponse.FromString,
                _registered_method=True)
        self.GetAllRates = channel.unary_unary(
                '/fx.FxService/GetAllRates',
                request_serializer=fx__pb2.AllRatesRequest.SerializeToString,
                response_deserializer=fx__pb2.AllRatesResponse.FromString,
                _registered_method=True)
        self.ConvertAmount = channel.unary_unary(
                '/fx.FxService/ConvertAmount',
                request_serializer=fx__pb2.ConvertAmountRequest.SerializeToString,
                response_deserializer=fx__pb2.ConvertAmountResponse.FromString,
                _registered_method=True)


class FxServiceServicer:
    """─── Servicio FX ────────────────────────────────────────
    """

    def GetExchangeRate(self, request, context):
        """Obtener tipo de cambio de una divisa
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllRates(self, request, context):
        """Obtener todos los tipos de cambio disponibles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertAmount(self, request, context):
        """Convertir un monto de USD a otra divisa
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetExchangeRate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExchangeRate,
                    request_deserializer=fx__pb2.ExchangeRateRequest.FromString,
                    response_serializer=fx__pb2.ExchangeRateResponse.SerializeToString,
            ),
            'GetAllRates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllRates,
                    request_deserializer=fx__pb2.AllRatesRequest.FromString,
                    response_serializer=fx__pb2.AllRatesResponse.SerializeToString,
            ),
            'ConvertAmount': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertAmount,
                    request_deserializer=fx__pb2.ConvertAmountRequest.FromString,
                    response_serializer=fx__pb2.ConvertAmountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fx.FxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fx.FxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FxService:
    """─── Servicio FX ────────────────────────────────────────
    """

    @staticmethod
    def GetExchangeRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.FxService/GetExchangeRate',
            fx__pb2.ExchangeRateRequest.SerializeToString,
            fx__pb2.ExchangeRateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllRates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.FxService/GetAllRates',
            fx__pb2.AllRatesRequest.SerializeToString,
            fx__pb2.AllRatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertAmount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fx.FxService/ConvertAmount',
            fx__pb2.ConvertAmountRequest.SerializeToString,
            fx__pb2.ConvertAmountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
