# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fx.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'fx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x66x.proto\x12\x02\x66x\"D\n\x13\x45xchangeRateRequest\x12\x17\n\x0ftarget_currency\x18\x01 \x01(\t\x12\x14\n\x0crequested_by\x18\x02 \x01(\t\"\'\n\x0f\x41llRatesRequest\x12\x14\n\x0crequested_by\x18\x01 \x01(\t\"U\n\x14\x43onvertAmountRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x01\x12\x17\n\x0ftarget_currency\x18\x02 \x01(\t\x12\x14\n\x0crequested_by\x18\x03 \x01(\t\"\xac\x01\n\x14\x45xchangeRateResponse\x12\x15\n\rcurrency_code\x18\x01 \x01(\t\x12\x15\n\rcurrency_name\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x0c\n\x04rate\x18\x04 \x01(\x01\x12\x0e\n\x06source\x18\x05 \x01(\t\x12\x10\n\x08valid_at\x18\x06 \x01(\t\x12\x0f\n\x07success\x18\x07 \x01(\x08\x12\x15\n\rerror_message\x18\x08 \x01(\t\"V\n\x08RateItem\x12\x15\n\rcurrency_code\x18\x01 \x01(\t\x12\x15\n\rcurrency_name\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x0c\n\x04rate\x18\x04 \x01(\x01\"W\n\x10\x41llRatesResponse\x12\x1b\n\x05rates\x18\x01 \x03(\x0b\x32\x0c.fx.RateItem\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\xa7\x01\n\x15\x43onvertAmountResponse\x12\x17\n\x0foriginal_amount\x18\x01 \x01(\x01\x12\x18\n\x10\x63onverted_amount\x18\x02 \x01(\x01\x12\x15\n\rcurrency_code\x18\x03 \x01(\t\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x0c\n\x04rate\x18\x05 \x01(\x01\x12\x0f\n\x07success\x18\x06 \x01(\x08\x12\x15\n\rerror_message\x18\x07 \x01(\t2\xd1\x01\n\tFxService\x12\x44\n\x0fGetExchangeRate\x12\x17.fx.ExchangeRateRequest\x1a\x18.fx.ExchangeRateResponse\x12\x38\n\x0bGetAllRates\x12\x13.fx.AllRatesRequest\x1a\x14.fx.AllRatesResponse\x12\x44\n\rConvertAmount\x12\x18.fx.ConvertAmountRequest\x1a\x19.fx.ConvertAmountResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXCHANGERATEREQUEST']._serialized_start=16
  _globals['_EXCHANGERATEREQUEST']._serialized_end=84
  _globals['_ALLRATESREQUEST']._serialized_start=86
  _globals['_ALLRATESREQUEST']._serialized_end=125
  _globals['_CONVERTAMOUNTREQUEST']._serialized_start=127
  _globals['_CONVERTAMOUNTREQUEST']._serialized_end=212
  _globals['_EXCHANGERATERESPONSE']._serialized_start=215
  _globals['_EXCHANGERATERESPONSE']._serialized_end=387
  _globals['_RATEITEM']._serialized_start=389
  _globals['_RATEITEM']._serialized_end=475
  _globals['_ALLRATESRESPONSE']._serialized_start=477
  _globals['_ALLRATESRESPONSE']._serialized_end=564
  _globals['_CONVERTAMOUNTRESPONSE']._serialized_start=567
  _globals['_CONVERTAMOUNTRESPONSE']._serialized_end=734
  _globals['_FXSERVICE']._serialized_start=737
  _globals['_FXSERVICE']._serialized_end=946
# @@protoc_insertion_point(module_scope)
