// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: catalog.proto

package catalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenreId       int32                  `protobuf:"varint,1,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Genre) GetGenreId() int32 {
	if x != nil {
		return x.GenreId
	}
	return 0
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Genre) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonId      string                 `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhotoUrl      string                 `protobuf:"bytes,3,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	RoleType      string                 `protobuf:"bytes,4,opt,name=role_type,json=roleType,proto3" json:"role_type,omitempty"` // ACTOR, DIRECTOR, WRITER
	CharacterName string                 `protobuf:"bytes,5,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	BillingOrder  int32                  `protobuf:"varint,6,opt,name=billing_order,json=billingOrder,proto3" json:"billing_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Person) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *Person) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Person) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *Person) GetRoleType() string {
	if x != nil {
		return x.RoleType
	}
	return ""
}

func (x *Person) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *Person) GetBillingOrder() int32 {
	if x != nil {
		return x.BillingOrder
	}
	return 0
}

// Tarjeta resumida para la cartelera/catálogo
type ContentCard struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ContentId         string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ContentType       string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // MOVIE | SERIES
	Title             string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ReleaseYear       int32                  `protobuf:"varint,4,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	DurationMin       int32                  `protobuf:"varint,5,opt,name=duration_min,json=durationMin,proto3" json:"duration_min,omitempty"`
	RatingClass       string                 `protobuf:"bytes,6,opt,name=rating_class,json=ratingClass,proto3" json:"rating_class,omitempty"`
	PosterUrl         string                 `protobuf:"bytes,7,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	Genres            []*Genre               `protobuf:"bytes,8,rep,name=genres,proto3" json:"genres,omitempty"`
	RecommendationPct float64                `protobuf:"fixed64,9,opt,name=recommendation_pct,json=recommendationPct,proto3" json:"recommendation_pct,omitempty"`
	AvgStars          float64                `protobuf:"fixed64,10,opt,name=avg_stars,json=avgStars,proto3" json:"avg_stars,omitempty"`
	TotalVotes        int64                  `protobuf:"varint,11,opt,name=total_votes,json=totalVotes,proto3" json:"total_votes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContentCard) Reset() {
	*x = ContentCard{}
	mi := &file_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentCard) ProtoMessage() {}

func (x *ContentCard) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentCard.ProtoReflect.Descriptor instead.
func (*ContentCard) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ContentCard) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ContentCard) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ContentCard) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContentCard) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *ContentCard) GetDurationMin() int32 {
	if x != nil {
		return x.DurationMin
	}
	return 0
}

func (x *ContentCard) GetRatingClass() string {
	if x != nil {
		return x.RatingClass
	}
	return ""
}

func (x *ContentCard) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *ContentCard) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *ContentCard) GetRecommendationPct() float64 {
	if x != nil {
		return x.RecommendationPct
	}
	return 0
}

func (x *ContentCard) GetAvgStars() float64 {
	if x != nil {
		return x.AvgStars
	}
	return 0
}

func (x *ContentCard) GetTotalVotes() int64 {
	if x != nil {
		return x.TotalVotes
	}
	return 0
}

// Ficha técnica completa
type ContentDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ContentId         string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ContentType       string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Title             string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	OriginalTitle     string                 `protobuf:"bytes,4,opt,name=original_title,json=originalTitle,proto3" json:"original_title,omitempty"`
	Synopsis          string                 `protobuf:"bytes,5,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	ReleaseYear       int32                  `protobuf:"varint,6,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	DurationMin       int32                  `protobuf:"varint,7,opt,name=duration_min,json=durationMin,proto3" json:"duration_min,omitempty"`
	RatingClass       string                 `protobuf:"bytes,8,opt,name=rating_class,json=ratingClass,proto3" json:"rating_class,omitempty"`
	PosterUrl         string                 `protobuf:"bytes,9,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	TrailerUrl        string                 `protobuf:"bytes,10,opt,name=trailer_url,json=trailerUrl,proto3" json:"trailer_url,omitempty"`
	VideoRef          string                 `protobuf:"bytes,11,opt,name=video_ref,json=videoRef,proto3" json:"video_ref,omitempty"`
	VideoSource       string                 `protobuf:"bytes,12,opt,name=video_source,json=videoSource,proto3" json:"video_source,omitempty"`
	Genres            []*Genre               `protobuf:"bytes,13,rep,name=genres,proto3" json:"genres,omitempty"`
	CastAndCrew       []*Person              `protobuf:"bytes,14,rep,name=cast_and_crew,json=castAndCrew,proto3" json:"cast_and_crew,omitempty"`
	RecommendationPct float64                `protobuf:"fixed64,15,opt,name=recommendation_pct,json=recommendationPct,proto3" json:"recommendation_pct,omitempty"`
	AvgStars          float64                `protobuf:"fixed64,16,opt,name=avg_stars,json=avgStars,proto3" json:"avg_stars,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContentDetail) Reset() {
	*x = ContentDetail{}
	mi := &file_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentDetail) ProtoMessage() {}

func (x *ContentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentDetail.ProtoReflect.Descriptor instead.
func (*ContentDetail) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ContentDetail) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ContentDetail) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ContentDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContentDetail) GetOriginalTitle() string {
	if x != nil {
		return x.OriginalTitle
	}
	return ""
}

func (x *ContentDetail) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *ContentDetail) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *ContentDetail) GetDurationMin() int32 {
	if x != nil {
		return x.DurationMin
	}
	return 0
}

func (x *ContentDetail) GetRatingClass() string {
	if x != nil {
		return x.RatingClass
	}
	return ""
}

func (x *ContentDetail) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *ContentDetail) GetTrailerUrl() string {
	if x != nil {
		return x.TrailerUrl
	}
	return ""
}

func (x *ContentDetail) GetVideoRef() string {
	if x != nil {
		return x.VideoRef
	}
	return ""
}

func (x *ContentDetail) GetVideoSource() string {
	if x != nil {
		return x.VideoSource
	}
	return ""
}

func (x *ContentDetail) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *ContentDetail) GetCastAndCrew() []*Person {
	if x != nil {
		return x.CastAndCrew
	}
	return nil
}

func (x *ContentDetail) GetRecommendationPct() float64 {
	if x != nil {
		return x.RecommendationPct
	}
	return 0
}

func (x *ContentDetail) GetAvgStars() float64 {
	if x != nil {
		return x.AvgStars
	}
	return 0
}

type Episode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpisodeId     string                 `protobuf:"bytes,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	EpisodeNum    int32                  `protobuf:"varint,2,opt,name=episode_num,json=episodeNum,proto3" json:"episode_num,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Synopsis      string                 `protobuf:"bytes,4,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	DurationMin   int32                  `protobuf:"varint,5,opt,name=duration_min,json=durationMin,proto3" json:"duration_min,omitempty"`
	VideoRef      string                 `protobuf:"bytes,6,opt,name=video_ref,json=videoRef,proto3" json:"video_ref,omitempty"`
	VideoSource   string                 `protobuf:"bytes,7,opt,name=video_source,json=videoSource,proto3" json:"video_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Episode) Reset() {
	*x = Episode{}
	mi := &file_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Episode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Episode) ProtoMessage() {}

func (x *Episode) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Episode.ProtoReflect.Descriptor instead.
func (*Episode) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *Episode) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *Episode) GetEpisodeNum() int32 {
	if x != nil {
		return x.EpisodeNum
	}
	return 0
}

func (x *Episode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Episode) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *Episode) GetDurationMin() int32 {
	if x != nil {
		return x.DurationMin
	}
	return 0
}

func (x *Episode) GetVideoRef() string {
	if x != nil {
		return x.VideoRef
	}
	return ""
}

func (x *Episode) GetVideoSource() string {
	if x != nil {
		return x.VideoSource
	}
	return ""
}

type Season struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeasonId      string                 `protobuf:"bytes,1,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`
	SeasonNum     int32                  `protobuf:"varint,2,opt,name=season_num,json=seasonNum,proto3" json:"season_num,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ReleaseYear   int32                  `protobuf:"varint,4,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	Episodes      []*Episode             `protobuf:"bytes,5,rep,name=episodes,proto3" json:"episodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Season) Reset() {
	*x = Season{}
	mi := &file_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Season) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Season) ProtoMessage() {}

func (x *Season) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Season.ProtoReflect.Descriptor instead.
func (*Season) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *Season) GetSeasonId() string {
	if x != nil {
		return x.SeasonId
	}
	return ""
}

func (x *Season) GetSeasonNum() int32 {
	if x != nil {
		return x.SeasonNum
	}
	return 0
}

func (x *Season) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Season) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *Season) GetEpisodes() []*Episode {
	if x != nil {
		return x.Episodes
	}
	return nil
}

type GetCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // "MOVIE", "SERIES", o vacío para ambos
	GenreId       int32                  `protobuf:"varint,2,opt,name=genre_id,json=genreId,proto3" json:"genre_id,omitempty"`            // 0 = sin filtro
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogRequest) Reset() {
	*x = GetCatalogRequest{}
	mi := &file_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogRequest) ProtoMessage() {}

func (x *GetCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetCatalogRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetCatalogRequest) GetGenreId() int32 {
	if x != nil {
		return x.GenreId
	}
	return 0
}

func (x *GetCatalogRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCatalogRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ContentCard         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogResponse) Reset() {
	*x = GetCatalogResponse{}
	mi := &file_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogResponse) ProtoMessage() {}

func (x *GetCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogResponse.ProtoReflect.Descriptor instead.
func (*GetCatalogResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *GetCatalogResponse) GetItems() []*ContentCard {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetCatalogResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetContentDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentDetailRequest) Reset() {
	*x = GetContentDetailRequest{}
	mi := &file_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentDetailRequest) ProtoMessage() {}

func (x *GetContentDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentDetailRequest.ProtoReflect.Descriptor instead.
func (*GetContentDetailRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *GetContentDetailRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type GetSeriesStructureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeriesStructureRequest) Reset() {
	*x = GetSeriesStructureRequest{}
	mi := &file_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeriesStructureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeriesStructureRequest) ProtoMessage() {}

func (x *GetSeriesStructureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeriesStructureRequest.ProtoReflect.Descriptor instead.
func (*GetSeriesStructureRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *GetSeriesStructureRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type GetSeriesStructureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	SeriesTitle   string                 `protobuf:"bytes,2,opt,name=series_title,json=seriesTitle,proto3" json:"series_title,omitempty"`
	Seasons       []*Season              `protobuf:"bytes,3,rep,name=seasons,proto3" json:"seasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeriesStructureResponse) Reset() {
	*x = GetSeriesStructureResponse{}
	mi := &file_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeriesStructureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeriesStructureResponse) ProtoMessage() {}

func (x *GetSeriesStructureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeriesStructureResponse.ProtoReflect.Descriptor instead.
func (*GetSeriesStructureResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *GetSeriesStructureResponse) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetSeriesStructureResponse) GetSeriesTitle() string {
	if x != nil {
		return x.SeriesTitle
	}
	return ""
}

func (x *GetSeriesStructureResponse) GetSeasons() []*Season {
	if x != nil {
		return x.Seasons
	}
	return nil
}

type SearchContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // "MOVIE", "SERIES", o vacío
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchContentRequest) Reset() {
	*x = SearchContentRequest{}
	mi := &file_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchContentRequest) ProtoMessage() {}

func (x *SearchContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchContentRequest.ProtoReflect.Descriptor instead.
func (*SearchContentRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *SearchContentRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchContentRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type SearchContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ContentCard         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchContentResponse) Reset() {
	*x = SearchContentResponse{}
	mi := &file_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchContentResponse) ProtoMessage() {}

func (x *SearchContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchContentResponse.ProtoReflect.Descriptor instead.
func (*SearchContentResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *SearchContentResponse) GetResults() []*ContentCard {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListGenresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGenresRequest) Reset() {
	*x = ListGenresRequest{}
	mi := &file_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGenresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGenresRequest) ProtoMessage() {}

func (x *ListGenresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGenresRequest.ProtoReflect.Descriptor instead.
func (*ListGenresRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{13}
}

type ListGenresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genres        []*Genre               `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGenresResponse) Reset() {
	*x = ListGenresResponse{}
	mi := &file_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGenresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGenresResponse) ProtoMessage() {}

func (x *ListGenresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGenresResponse.ProtoReflect.Descriptor instead.
func (*ListGenresResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *ListGenresResponse) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

type GetPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonId      string                 `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonRequest) Reset() {
	*x = GetPersonRequest{}
	mi := &file_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonRequest) ProtoMessage() {}

func (x *GetPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonRequest.ProtoReflect.Descriptor instead.
func (*GetPersonRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *GetPersonRequest) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

type PersonDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonId      string                 `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	BirthDate     string                 `protobuf:"bytes,3,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Nationality   string                 `protobuf:"bytes,4,opt,name=nationality,proto3" json:"nationality,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	PhotoUrl      string                 `protobuf:"bytes,6,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonDetail) Reset() {
	*x = PersonDetail{}
	mi := &file_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonDetail) ProtoMessage() {}

func (x *PersonDetail) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonDetail.ProtoReflect.Descriptor instead.
func (*PersonDetail) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *PersonDetail) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *PersonDetail) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *PersonDetail) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *PersonDetail) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *PersonDetail) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *PersonDetail) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

type RateContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"` // extraído del JWT por el API Gateway
	Thumb         string                 `protobuf:"bytes,3,opt,name=thumb,proto3" json:"thumb,omitempty"`                          // "UP", "DOWN", o vacío
	Stars         int32                  `protobuf:"varint,4,opt,name=stars,proto3" json:"stars,omitempty"`                         // 1-5, o 0 si no aplica
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateContentRequest) Reset() {
	*x = RateContentRequest{}
	mi := &file_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateContentRequest) ProtoMessage() {}

func (x *RateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateContentRequest.ProtoReflect.Descriptor instead.
func (*RateContentRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *RateContentRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *RateContentRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *RateContentRequest) GetThumb() string {
	if x != nil {
		return x.Thumb
	}
	return ""
}

func (x *RateContentRequest) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

type RateContentResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RecommendationPct float64                `protobuf:"fixed64,2,opt,name=recommendation_pct,json=recommendationPct,proto3" json:"recommendation_pct,omitempty"`
	AvgStars          float64                `protobuf:"fixed64,3,opt,name=avg_stars,json=avgStars,proto3" json:"avg_stars,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RateContentResponse) Reset() {
	*x = RateContentResponse{}
	mi := &file_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateContentResponse) ProtoMessage() {}

func (x *RateContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateContentResponse.ProtoReflect.Descriptor instead.
func (*RateContentResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *RateContentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RateContentResponse) GetRecommendationPct() float64 {
	if x != nil {
		return x.RecommendationPct
	}
	return 0
}

func (x *RateContentResponse) GetAvgStars() float64 {
	if x != nil {
		return x.AvgStars
	}
	return 0
}

type GetUserRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRatingRequest) Reset() {
	*x = GetUserRatingRequest{}
	mi := &file_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRatingRequest) ProtoMessage() {}

func (x *GetUserRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRatingRequest.ProtoReflect.Descriptor instead.
func (*GetUserRatingRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserRatingRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetUserRatingRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type UserRating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Thumb         string                 `protobuf:"bytes,3,opt,name=thumb,proto3" json:"thumb,omitempty"`
	Stars         int32                  `protobuf:"varint,4,opt,name=stars,proto3" json:"stars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRating) Reset() {
	*x = UserRating{}
	mi := &file_catalog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRating) ProtoMessage() {}

func (x *UserRating) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRating.ProtoReflect.Descriptor instead.
func (*UserRating) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{20}
}

func (x *UserRating) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *UserRating) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *UserRating) GetThumb() string {
	if x != nil {
		return x.Thumb
	}
	return ""
}

func (x *UserRating) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

type CreateContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	OriginalTitle string                 `protobuf:"bytes,3,opt,name=original_title,json=originalTitle,proto3" json:"original_title,omitempty"`
	Synopsis      string                 `protobuf:"bytes,4,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	ReleaseYear   int32                  `protobuf:"varint,5,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	DurationMin   int32                  `protobuf:"varint,6,opt,name=duration_min,json=durationMin,proto3" json:"duration_min,omitempty"`
	RatingClass   string                 `protobuf:"bytes,7,opt,name=rating_class,json=ratingClass,proto3" json:"rating_class,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,8,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	TrailerUrl    string                 `protobuf:"bytes,9,opt,name=trailer_url,json=trailerUrl,proto3" json:"trailer_url,omitempty"`
	VideoRef      string                 `protobuf:"bytes,10,opt,name=video_ref,json=videoRef,proto3" json:"video_ref,omitempty"`
	VideoSource   string                 `protobuf:"bytes,11,opt,name=video_source,json=videoSource,proto3" json:"video_source,omitempty"`
	GenreIds      []int32                `protobuf:"varint,12,rep,packed,name=genre_ids,json=genreIds,proto3" json:"genre_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentRequest) Reset() {
	*x = CreateContentRequest{}
	mi := &file_catalog_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentRequest) ProtoMessage() {}

func (x *CreateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentRequest.ProtoReflect.Descriptor instead.
func (*CreateContentRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{21}
}

func (x *CreateContentRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateContentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateContentRequest) GetOriginalTitle() string {
	if x != nil {
		return x.OriginalTitle
	}
	return ""
}

func (x *CreateContentRequest) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *CreateContentRequest) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *CreateContentRequest) GetDurationMin() int32 {
	if x != nil {
		return x.DurationMin
	}
	return 0
}

func (x *CreateContentRequest) GetRatingClass() string {
	if x != nil {
		return x.RatingClass
	}
	return ""
}

func (x *CreateContentRequest) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *CreateContentRequest) GetTrailerUrl() string {
	if x != nil {
		return x.TrailerUrl
	}
	return ""
}

func (x *CreateContentRequest) GetVideoRef() string {
	if x != nil {
		return x.VideoRef
	}
	return ""
}

func (x *CreateContentRequest) GetVideoSource() string {
	if x != nil {
		return x.VideoSource
	}
	return ""
}

func (x *CreateContentRequest) GetGenreIds() []int32 {
	if x != nil {
		return x.GenreIds
	}
	return nil
}

type UpdateContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Synopsis      string                 `protobuf:"bytes,3,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,4,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	TrailerUrl    string                 `protobuf:"bytes,5,opt,name=trailer_url,json=trailerUrl,proto3" json:"trailer_url,omitempty"`
	VideoRef      string                 `protobuf:"bytes,6,opt,name=video_ref,json=videoRef,proto3" json:"video_ref,omitempty"`
	GenreIds      []int32                `protobuf:"varint,7,rep,packed,name=genre_ids,json=genreIds,proto3" json:"genre_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContentRequest) Reset() {
	*x = UpdateContentRequest{}
	mi := &file_catalog_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContentRequest) ProtoMessage() {}

func (x *UpdateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContentRequest.ProtoReflect.Descriptor instead.
func (*UpdateContentRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateContentRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *UpdateContentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateContentRequest) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *UpdateContentRequest) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *UpdateContentRequest) GetTrailerUrl() string {
	if x != nil {
		return x.TrailerUrl
	}
	return ""
}

func (x *UpdateContentRequest) GetVideoRef() string {
	if x != nil {
		return x.VideoRef
	}
	return ""
}

func (x *UpdateContentRequest) GetGenreIds() []int32 {
	if x != nil {
		return x.GenreIds
	}
	return nil
}

type PublishContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishContentRequest) Reset() {
	*x = PublishContentRequest{}
	mi := &file_catalog_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishContentRequest) ProtoMessage() {}

func (x *PublishContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishContentRequest.ProtoReflect.Descriptor instead.
func (*PublishContentRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{23}
}

func (x *PublishContentRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type PublishContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,2,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishContentResponse) Reset() {
	*x = PublishContentResponse{}
	mi := &file_catalog_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishContentResponse) ProtoMessage() {}

func (x *PublishContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishContentResponse.ProtoReflect.Descriptor instead.
func (*PublishContentResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{24}
}

func (x *PublishContentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishContentResponse) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

type AddPersonToContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	PersonId      string                 `protobuf:"bytes,2,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	RoleType      string                 `protobuf:"bytes,3,opt,name=role_type,json=roleType,proto3" json:"role_type,omitempty"` // ACTOR, DIRECTOR, WRITER
	CharacterName string                 `protobuf:"bytes,4,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	BillingOrder  int32                  `protobuf:"varint,5,opt,name=billing_order,json=billingOrder,proto3" json:"billing_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPersonToContentRequest) Reset() {
	*x = AddPersonToContentRequest{}
	mi := &file_catalog_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPersonToContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPersonToContentRequest) ProtoMessage() {}

func (x *AddPersonToContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPersonToContentRequest.ProtoReflect.Descriptor instead.
func (*AddPersonToContentRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{25}
}

func (x *AddPersonToContentRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *AddPersonToContentRequest) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *AddPersonToContentRequest) GetRoleType() string {
	if x != nil {
		return x.RoleType
	}
	return ""
}

func (x *AddPersonToContentRequest) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *AddPersonToContentRequest) GetBillingOrder() int32 {
	if x != nil {
		return x.BillingOrder
	}
	return 0
}

type AddPersonToContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPersonToContentResponse) Reset() {
	*x = AddPersonToContentResponse{}
	mi := &file_catalog_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPersonToContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPersonToContentResponse) ProtoMessage() {}

func (x *AddPersonToContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPersonToContentResponse.ProtoReflect.Descriptor instead.
func (*AddPersonToContentResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{26}
}

func (x *AddPersonToContentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreatePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	BirthDate     string                 `protobuf:"bytes,2,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Nationality   string                 `protobuf:"bytes,3,opt,name=nationality,proto3" json:"nationality,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	PhotoUrl      string                 `protobuf:"bytes,5,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonRequest) Reset() {
	*x = CreatePersonRequest{}
	mi := &file_catalog_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonRequest) ProtoMessage() {}

func (x *CreatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonRequest.ProtoReflect.Descriptor instead.
func (*CreatePersonRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{27}
}

func (x *CreatePersonRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreatePersonRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *CreatePersonRequest) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *CreatePersonRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *CreatePersonRequest) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

var File_catalog_proto protoreflect.FileDescriptor

const file_catalog_proto_rawDesc = "" +
	"\n" +
	"\rcatalog.proto\x12\acatalog\"J\n" +
	"\x05Genre\x12\x19\n" +
	"\bgenre_id\x18\x01 \x01(\x05R\agenreId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\"\xc8\x01\n" +
	"\x06Person\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x1b\n" +
	"\tphoto_url\x18\x03 \x01(\tR\bphotoUrl\x12\x1b\n" +
	"\trole_type\x18\x04 \x01(\tR\broleType\x12%\n" +
	"\x0echaracter_name\x18\x05 \x01(\tR\rcharacterName\x12#\n" +
	"\rbilling_order\x18\x06 \x01(\x05R\fbillingOrder\"\x82\x03\n" +
	"\vContentCard\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12!\n" +
	"\frelease_year\x18\x04 \x01(\x05R\vreleaseYear\x12!\n" +
	"\fduration_min\x18\x05 \x01(\x05R\vdurationMin\x12!\n" +
	"\frating_class\x18\x06 \x01(\tR\vratingClass\x12\x1d\n" +
	"\n" +
	"poster_url\x18\a \x01(\tR\tposterUrl\x12&\n" +
	"\x06genres\x18\b \x03(\v2\x0e.catalog.GenreR\x06genres\x12-\n" +
	"\x12recommendation_pct\x18\t \x01(\x01R\x11recommendationPct\x12\x1b\n" +
	"\tavg_stars\x18\n" +
	" \x01(\x01R\bavgStars\x12\x1f\n" +
	"\vtotal_votes\x18\v \x01(\x03R\n" +
	"totalVotes\"\xbc\x04\n" +
	"\rContentDetail\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12%\n" +
	"\x0eoriginal_title\x18\x04 \x01(\tR\roriginalTitle\x12\x1a\n" +
	"\bsynopsis\x18\x05 \x01(\tR\bsynopsis\x12!\n" +
	"\frelease_year\x18\x06 \x01(\x05R\vreleaseYear\x12!\n" +
	"\fduration_min\x18\a \x01(\x05R\vdurationMin\x12!\n" +
	"\frating_class\x18\b \x01(\tR\vratingClass\x12\x1d\n" +
	"\n" +
	"poster_url\x18\t \x01(\tR\tposterUrl\x12\x1f\n" +
	"\vtrailer_url\x18\n" +
	" \x01(\tR\n" +
	"trailerUrl\x12\x1b\n" +
	"\tvideo_ref\x18\v \x01(\tR\bvideoRef\x12!\n" +
	"\fvideo_source\x18\f \x01(\tR\vvideoSource\x12&\n" +
	"\x06genres\x18\r \x03(\v2\x0e.catalog.GenreR\x06genres\x123\n" +
	"\rcast_and_crew\x18\x0e \x03(\v2\x0f.catalog.PersonR\vcastAndCrew\x12-\n" +
	"\x12recommendation_pct\x18\x0f \x01(\x01R\x11recommendationPct\x12\x1b\n" +
	"\tavg_stars\x18\x10 \x01(\x01R\bavgStars\"\xde\x01\n" +
	"\aEpisode\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\tR\tepisodeId\x12\x1f\n" +
	"\vepisode_num\x18\x02 \x01(\x05R\n" +
	"episodeNum\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bsynopsis\x18\x04 \x01(\tR\bsynopsis\x12!\n" +
	"\fduration_min\x18\x05 \x01(\x05R\vdurationMin\x12\x1b\n" +
	"\tvideo_ref\x18\x06 \x01(\tR\bvideoRef\x12!\n" +
	"\fvideo_source\x18\a \x01(\tR\vvideoSource\"\xab\x01\n" +
	"\x06Season\x12\x1b\n" +
	"\tseason_id\x18\x01 \x01(\tR\bseasonId\x12\x1d\n" +
	"\n" +
	"season_num\x18\x02 \x01(\x05R\tseasonNum\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12!\n" +
	"\frelease_year\x18\x04 \x01(\x05R\vreleaseYear\x12,\n" +
	"\bepisodes\x18\x05 \x03(\v2\x10.catalog.EpisodeR\bepisodes\"\x82\x01\n" +
	"\x11GetCatalogRequest\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x19\n" +
	"\bgenre_id\x18\x02 \x01(\x05R\agenreId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"V\n" +
	"\x12GetCatalogResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.catalog.ContentCardR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"8\n" +
	"\x17GetContentDetailRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\":\n" +
	"\x19GetSeriesStructureRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"\x89\x01\n" +
	"\x1aGetSeriesStructureResponse\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12!\n" +
	"\fseries_title\x18\x02 \x01(\tR\vseriesTitle\x12)\n" +
	"\aseasons\x18\x03 \x03(\v2\x0f.catalog.SeasonR\aseasons\"O\n" +
	"\x14SearchContentRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"G\n" +
	"\x15SearchContentResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.catalog.ContentCardR\aresults\"\x13\n" +
	"\x11ListGenresRequest\"<\n" +
	"\x12ListGenresResponse\x12&\n" +
	"\x06genres\x18\x01 \x03(\v2\x0e.catalog.GenreR\x06genres\"/\n" +
	"\x10GetPersonRequest\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\"\xb8\x01\n" +
	"\fPersonDetail\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x03 \x01(\tR\tbirthDate\x12 \n" +
	"\vnationality\x18\x04 \x01(\tR\vnationality\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1b\n" +
	"\tphoto_url\x18\x06 \x01(\tR\bphotoUrl\"~\n" +
	"\x12RateContentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x14\n" +
	"\x05thumb\x18\x03 \x01(\tR\x05thumb\x12\x14\n" +
	"\x05stars\x18\x04 \x01(\x05R\x05stars\"{\n" +
	"\x13RateContentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\x12recommendation_pct\x18\x02 \x01(\x01R\x11recommendationPct\x12\x1b\n" +
	"\tavg_stars\x18\x03 \x01(\x01R\bavgStars\"T\n" +
	"\x14GetUserRatingRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\"v\n" +
	"\n" +
	"UserRating\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x14\n" +
	"\x05thumb\x18\x03 \x01(\tR\x05thumb\x12\x14\n" +
	"\x05stars\x18\x04 \x01(\x05R\x05stars\"\x98\x03\n" +
	"\x14CreateContentRequest\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x0eoriginal_title\x18\x03 \x01(\tR\roriginalTitle\x12\x1a\n" +
	"\bsynopsis\x18\x04 \x01(\tR\bsynopsis\x12!\n" +
	"\frelease_year\x18\x05 \x01(\x05R\vreleaseYear\x12!\n" +
	"\fduration_min\x18\x06 \x01(\x05R\vdurationMin\x12!\n" +
	"\frating_class\x18\a \x01(\tR\vratingClass\x12\x1d\n" +
	"\n" +
	"poster_url\x18\b \x01(\tR\tposterUrl\x12\x1f\n" +
	"\vtrailer_url\x18\t \x01(\tR\n" +
	"trailerUrl\x12\x1b\n" +
	"\tvideo_ref\x18\n" +
	" \x01(\tR\bvideoRef\x12!\n" +
	"\fvideo_source\x18\v \x01(\tR\vvideoSource\x12\x1b\n" +
	"\tgenre_ids\x18\f \x03(\x05R\bgenreIds\"\xe1\x01\n" +
	"\x14UpdateContentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bsynopsis\x18\x03 \x01(\tR\bsynopsis\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x04 \x01(\tR\tposterUrl\x12\x1f\n" +
	"\vtrailer_url\x18\x05 \x01(\tR\n" +
	"trailerUrl\x12\x1b\n" +
	"\tvideo_ref\x18\x06 \x01(\tR\bvideoRef\x12\x1b\n" +
	"\tgenre_ids\x18\a \x03(\x05R\bgenreIds\"6\n" +
	"\x15PublishContentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"U\n" +
	"\x16PublishContentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fpublished_at\x18\x02 \x01(\tR\vpublishedAt\"\xc0\x01\n" +
	"\x19AddPersonToContentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x1b\n" +
	"\tperson_id\x18\x02 \x01(\tR\bpersonId\x12\x1b\n" +
	"\trole_type\x18\x03 \x01(\tR\broleType\x12%\n" +
	"\x0echaracter_name\x18\x04 \x01(\tR\rcharacterName\x12#\n" +
	"\rbilling_order\x18\x05 \x01(\x05R\fbillingOrder\"6\n" +
	"\x1aAddPersonToContentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa2\x01\n" +
	"\x13CreatePersonRequest\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x02 \x01(\tR\tbirthDate\x12 \n" +
	"\vnationality\x18\x03 \x01(\tR\vnationality\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x1b\n" +
	"\tphoto_url\x18\x05 \x01(\tR\bphotoUrl2\xec\a\n" +
	"\x0eCatalogService\x12E\n" +
	"\n" +
	"GetCatalog\x12\x1a.catalog.GetCatalogRequest\x1a\x1b.catalog.GetCatalogResponse\x12L\n" +
	"\x10GetContentDetail\x12 .catalog.GetContentDetailRequest\x1a\x16.catalog.ContentDetail\x12]\n" +
	"\x12GetSeriesStructure\x12\".catalog.GetSeriesStructureRequest\x1a#.catalog.GetSeriesStructureResponse\x12N\n" +
	"\rSearchContent\x12\x1d.catalog.SearchContentRequest\x1a\x1e.catalog.SearchContentResponse\x12E\n" +
	"\n" +
	"ListGenres\x12\x1a.catalog.ListGenresRequest\x1a\x1b.catalog.ListGenresResponse\x12=\n" +
	"\tGetPerson\x12\x19.catalog.GetPersonRequest\x1a\x15.catalog.PersonDetail\x12H\n" +
	"\vRateContent\x12\x1b.catalog.RateContentRequest\x1a\x1c.catalog.RateContentResponse\x12C\n" +
	"\rGetUserRating\x12\x1d.catalog.GetUserRatingRequest\x1a\x13.catalog.UserRating\x12D\n" +
	"\rCreateContent\x12\x1d.catalog.CreateContentRequest\x1a\x14.catalog.ContentCard\x12D\n" +
	"\rUpdateContent\x12\x1d.catalog.UpdateContentRequest\x1a\x14.catalog.ContentCard\x12Q\n" +
	"\x0ePublishContent\x12\x1e.catalog.PublishContentRequest\x1a\x1f.catalog.PublishContentResponse\x12C\n" +
	"\fCreatePerson\x12\x1c.catalog.CreatePersonRequest\x1a\x15.catalog.PersonDetail\x12]\n" +
	"\x12AddPersonToContent\x12\".catalog.AddPersonToContentRequest\x1a#.catalog.AddPersonToContentResponseB4Z2github.com/quetxaltv/catalog-service/proto/catalogb\x06proto3"

var (
	file_catalog_proto_rawDescOnce sync.Once
	file_catalog_proto_rawDescData []byte
)

func file_catalog_proto_rawDescGZIP() []byte {
	file_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)))
	})
	return file_catalog_proto_rawDescData
}

var file_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_catalog_proto_goTypes = []any{
	(*Genre)(nil),                      // 0: catalog.Genre
	(*Person)(nil),                     // 1: catalog.Person
	(*ContentCard)(nil),                // 2: catalog.ContentCard
	(*ContentDetail)(nil),              // 3: catalog.ContentDetail
	(*Episode)(nil),                    // 4: catalog.Episode
	(*Season)(nil),                     // 5: catalog.Season
	(*GetCatalogRequest)(nil),          // 6: catalog.GetCatalogRequest
	(*GetCatalogResponse)(nil),         // 7: catalog.GetCatalogResponse
	(*GetContentDetailRequest)(nil),    // 8: catalog.GetContentDetailRequest
	(*GetSeriesStructureRequest)(nil),  // 9: catalog.GetSeriesStructureRequest
	(*GetSeriesStructureResponse)(nil), // 10: catalog.GetSeriesStructureResponse
	(*SearchContentRequest)(nil),       // 11: catalog.SearchContentRequest
	(*SearchContentResponse)(nil),      // 12: catalog.SearchContentResponse
	(*ListGenresRequest)(nil),          // 13: catalog.ListGenresRequest
	(*ListGenresResponse)(nil),         // 14: catalog.ListGenresResponse
	(*GetPersonRequest)(nil),           // 15: catalog.GetPersonRequest
	(*PersonDetail)(nil),               // 16: catalog.PersonDetail
	(*RateContentRequest)(nil),         // 17: catalog.RateContentRequest
	(*RateContentResponse)(nil),        // 18: catalog.RateContentResponse
	(*GetUserRatingRequest)(nil),       // 19: catalog.GetUserRatingRequest
	(*UserRating)(nil),                 // 20: catalog.UserRating
	(*CreateContentRequest)(nil),       // 21: catalog.CreateContentRequest
	(*UpdateContentRequest)(nil),       // 22: catalog.UpdateContentRequest
	(*PublishContentRequest)(nil),      // 23: catalog.PublishContentRequest
	(*PublishContentResponse)(nil),     // 24: catalog.PublishContentResponse
	(*AddPersonToContentRequest)(nil),  // 25: catalog.AddPersonToContentRequest
	(*AddPersonToContentResponse)(nil), // 26: catalog.AddPersonToContentResponse
	(*CreatePersonRequest)(nil),        // 27: catalog.CreatePersonRequest
}
var file_catalog_proto_depIdxs = []int32{
	0,  // 0: catalog.ContentCard.genres:type_name -> catalog.Genre
	0,  // 1: catalog.ContentDetail.genres:type_name -> catalog.Genre
	1,  // 2: catalog.ContentDetail.cast_and_crew:type_name -> catalog.Person
	4,  // 3: catalog.Season.episodes:type_name -> catalog.Episode
	2,  // 4: catalog.GetCatalogResponse.items:type_name -> catalog.ContentCard
	5,  // 5: catalog.GetSeriesStructureResponse.seasons:type_name -> catalog.Season
	2,  // 6: catalog.SearchContentResponse.results:type_name -> catalog.ContentCard
	0,  // 7: catalog.ListGenresResponse.genres:type_name -> catalog.Genre
	6,  // 8: catalog.CatalogService.GetCatalog:input_type -> catalog.GetCatalogRequest
	8,  // 9: catalog.CatalogService.GetContentDetail:input_type -> catalog.GetContentDetailRequest
	9,  // 10: catalog.CatalogService.GetSeriesStructure:input_type -> catalog.GetSeriesStructureRequest
	11, // 11: catalog.CatalogService.SearchContent:input_type -> catalog.SearchContentRequest
	13, // 12: catalog.CatalogService.ListGenres:input_type -> catalog.ListGenresRequest
	15, // 13: catalog.CatalogService.GetPerson:input_type -> catalog.GetPersonRequest
	17, // 14: catalog.CatalogService.RateContent:input_type -> catalog.RateContentRequest
	19, // 15: catalog.CatalogService.GetUserRating:input_type -> catalog.GetUserRatingRequest
	21, // 16: catalog.CatalogService.CreateContent:input_type -> catalog.CreateContentRequest
	22, // 17: catalog.CatalogService.UpdateContent:input_type -> catalog.UpdateContentRequest
	23, // 18: catalog.CatalogService.PublishContent:input_type -> catalog.PublishContentRequest
	27, // 19: catalog.CatalogService.CreatePerson:input_type -> catalog.CreatePersonRequest
	25, // 20: catalog.CatalogService.AddPersonToContent:input_type -> catalog.AddPersonToContentRequest
	7,  // 21: catalog.CatalogService.GetCatalog:output_type -> catalog.GetCatalogResponse
	3,  // 22: catalog.CatalogService.GetContentDetail:output_type -> catalog.ContentDetail
	10, // 23: catalog.CatalogService.GetSeriesStructure:output_type -> catalog.GetSeriesStructureResponse
	12, // 24: catalog.CatalogService.SearchContent:output_type -> catalog.SearchContentResponse
	14, // 25: catalog.CatalogService.ListGenres:output_type -> catalog.ListGenresResponse
	16, // 26: catalog.CatalogService.GetPerson:output_type -> catalog.PersonDetail
	18, // 27: catalog.CatalogService.RateContent:output_type -> catalog.RateContentResponse
	20, // 28: catalog.CatalogService.GetUserRating:output_type -> catalog.UserRating
	2,  // 29: catalog.CatalogService.CreateContent:output_type -> catalog.ContentCard
	2,  // 30: catalog.CatalogService.UpdateContent:output_type -> catalog.ContentCard
	24, // 31: catalog.CatalogService.PublishContent:output_type -> catalog.PublishContentResponse
	16, // 32: catalog.CatalogService.CreatePerson:output_type -> catalog.PersonDetail
	26, // 33: catalog.CatalogService.AddPersonToContent:output_type -> catalog.AddPersonToContentResponse
	21, // [21:34] is the sub-list for method output_type
	8,  // [8:21] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_catalog_proto_init() }
func file_catalog_proto_init() {
	if File_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_proto_msgTypes,
	}.Build()
	File_catalog_proto = out.File
	file_catalog_proto_goTypes = nil
	file_catalog_proto_depIdxs = nil
}
