// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: catalog.proto

package catalog

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_GetCatalog_FullMethodName         = "/catalog.CatalogService/GetCatalog"
	CatalogService_GetContentDetail_FullMethodName   = "/catalog.CatalogService/GetContentDetail"
	CatalogService_GetSeriesStructure_FullMethodName = "/catalog.CatalogService/GetSeriesStructure"
	CatalogService_SearchContent_FullMethodName      = "/catalog.CatalogService/SearchContent"
	CatalogService_ListGenres_FullMethodName         = "/catalog.CatalogService/ListGenres"
	CatalogService_GetPerson_FullMethodName          = "/catalog.CatalogService/GetPerson"
	CatalogService_RateContent_FullMethodName        = "/catalog.CatalogService/RateContent"
	CatalogService_GetUserRating_FullMethodName      = "/catalog.CatalogService/GetUserRating"
	CatalogService_CreateContent_FullMethodName      = "/catalog.CatalogService/CreateContent"
	CatalogService_UpdateContent_FullMethodName      = "/catalog.CatalogService/UpdateContent"
	CatalogService_PublishContent_FullMethodName     = "/catalog.CatalogService/PublishContent"
	CatalogService_CreatePerson_FullMethodName       = "/catalog.CatalogService/CreatePerson"
	CatalogService_AddPersonToContent_FullMethodName = "/catalog.CatalogService/AddPersonToContent"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	// Catálogo público
	GetCatalog(ctx context.Context, in *GetCatalogRequest, opts ...grpc.CallOption) (*GetCatalogResponse, error)
	GetContentDetail(ctx context.Context, in *GetContentDetailRequest, opts ...grpc.CallOption) (*ContentDetail, error)
	GetSeriesStructure(ctx context.Context, in *GetSeriesStructureRequest, opts ...grpc.CallOption) (*GetSeriesStructureResponse, error)
	SearchContent(ctx context.Context, in *SearchContentRequest, opts ...grpc.CallOption) (*SearchContentResponse, error)
	// Géneros y personas
	ListGenres(ctx context.Context, in *ListGenresRequest, opts ...grpc.CallOption) (*ListGenresResponse, error)
	GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*PersonDetail, error)
	// Calificaciones
	RateContent(ctx context.Context, in *RateContentRequest, opts ...grpc.CallOption) (*RateContentResponse, error)
	GetUserRating(ctx context.Context, in *GetUserRatingRequest, opts ...grpc.CallOption) (*UserRating, error)
	// Admin
	CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*ContentCard, error)
	UpdateContent(ctx context.Context, in *UpdateContentRequest, opts ...grpc.CallOption) (*ContentCard, error)
	PublishContent(ctx context.Context, in *PublishContentRequest, opts ...grpc.CallOption) (*PublishContentResponse, error)
	CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*PersonDetail, error)
	AddPersonToContent(ctx context.Context, in *AddPersonToContentRequest, opts ...grpc.CallOption) (*AddPersonToContentResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) GetCatalog(ctx context.Context, in *GetCatalogRequest, opts ...grpc.CallOption) (*GetCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCatalogResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetContentDetail(ctx context.Context, in *GetContentDetailRequest, opts ...grpc.CallOption) (*ContentDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentDetail)
	err := c.cc.Invoke(ctx, CatalogService_GetContentDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetSeriesStructure(ctx context.Context, in *GetSeriesStructureRequest, opts ...grpc.CallOption) (*GetSeriesStructureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeriesStructureResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetSeriesStructure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) SearchContent(ctx context.Context, in *SearchContentRequest, opts ...grpc.CallOption) (*SearchContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchContentResponse)
	err := c.cc.Invoke(ctx, CatalogService_SearchContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListGenres(ctx context.Context, in *ListGenresRequest, opts ...grpc.CallOption) (*ListGenresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGenresResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListGenres_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*PersonDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersonDetail)
	err := c.cc.Invoke(ctx, CatalogService_GetPerson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) RateContent(ctx context.Context, in *RateContentRequest, opts ...grpc.CallOption) (*RateContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RateContentResponse)
	err := c.cc.Invoke(ctx, CatalogService_RateContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetUserRating(ctx context.Context, in *GetUserRatingRequest, opts ...grpc.CallOption) (*UserRating, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserRating)
	err := c.cc.Invoke(ctx, CatalogService_GetUserRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateContent(ctx context.Context, in *CreateContentRequest, opts ...grpc.CallOption) (*ContentCard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentCard)
	err := c.cc.Invoke(ctx, CatalogService_CreateContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateContent(ctx context.Context, in *UpdateContentRequest, opts ...grpc.CallOption) (*ContentCard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentCard)
	err := c.cc.Invoke(ctx, CatalogService_UpdateContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) PublishContent(ctx context.Context, in *PublishContentRequest, opts ...grpc.CallOption) (*PublishContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishContentResponse)
	err := c.cc.Invoke(ctx, CatalogService_PublishContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreatePerson(ctx context.Context, in *CreatePersonRequest, opts ...grpc.CallOption) (*PersonDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersonDetail)
	err := c.cc.Invoke(ctx, CatalogService_CreatePerson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) AddPersonToContent(ctx context.Context, in *AddPersonToContentRequest, opts ...grpc.CallOption) (*AddPersonToContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPersonToContentResponse)
	err := c.cc.Invoke(ctx, CatalogService_AddPersonToContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
type CatalogServiceServer interface {
	// Catálogo público
	GetCatalog(context.Context, *GetCatalogRequest) (*GetCatalogResponse, error)
	GetContentDetail(context.Context, *GetContentDetailRequest) (*ContentDetail, error)
	GetSeriesStructure(context.Context, *GetSeriesStructureRequest) (*GetSeriesStructureResponse, error)
	SearchContent(context.Context, *SearchContentRequest) (*SearchContentResponse, error)
	// Géneros y personas
	ListGenres(context.Context, *ListGenresRequest) (*ListGenresResponse, error)
	GetPerson(context.Context, *GetPersonRequest) (*PersonDetail, error)
	// Calificaciones
	RateContent(context.Context, *RateContentRequest) (*RateContentResponse, error)
	GetUserRating(context.Context, *GetUserRatingRequest) (*UserRating, error)
	// Admin
	CreateContent(context.Context, *CreateContentRequest) (*ContentCard, error)
	UpdateContent(context.Context, *UpdateContentRequest) (*ContentCard, error)
	PublishContent(context.Context, *PublishContentRequest) (*PublishContentResponse, error)
	CreatePerson(context.Context, *CreatePersonRequest) (*PersonDetail, error)
	AddPersonToContent(context.Context, *AddPersonToContentRequest) (*AddPersonToContentResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) GetCatalog(context.Context, *GetCatalogRequest) (*GetCatalogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCatalog not implemented")
}
func (UnimplementedCatalogServiceServer) GetContentDetail(context.Context, *GetContentDetailRequest) (*ContentDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContentDetail not implemented")
}
func (UnimplementedCatalogServiceServer) GetSeriesStructure(context.Context, *GetSeriesStructureRequest) (*GetSeriesStructureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeriesStructure not implemented")
}
func (UnimplementedCatalogServiceServer) SearchContent(context.Context, *SearchContentRequest) (*SearchContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchContent not implemented")
}
func (UnimplementedCatalogServiceServer) ListGenres(context.Context, *ListGenresRequest) (*ListGenresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGenres not implemented")
}
func (UnimplementedCatalogServiceServer) GetPerson(context.Context, *GetPersonRequest) (*PersonDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPerson not implemented")
}
func (UnimplementedCatalogServiceServer) RateContent(context.Context, *RateContentRequest) (*RateContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RateContent not implemented")
}
func (UnimplementedCatalogServiceServer) GetUserRating(context.Context, *GetUserRatingRequest) (*UserRating, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRating not implemented")
}
func (UnimplementedCatalogServiceServer) CreateContent(context.Context, *CreateContentRequest) (*ContentCard, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateContent not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateContent(context.Context, *UpdateContentRequest) (*ContentCard, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateContent not implemented")
}
func (UnimplementedCatalogServiceServer) PublishContent(context.Context, *PublishContentRequest) (*PublishContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishContent not implemented")
}
func (UnimplementedCatalogServiceServer) CreatePerson(context.Context, *CreatePersonRequest) (*PersonDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePerson not implemented")
}
func (UnimplementedCatalogServiceServer) AddPersonToContent(context.Context, *AddPersonToContentRequest) (*AddPersonToContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPersonToContent not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_GetCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetCatalog(ctx, req.(*GetCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetContentDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetContentDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetContentDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetContentDetail(ctx, req.(*GetContentDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetSeriesStructure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeriesStructureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetSeriesStructure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetSeriesStructure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetSeriesStructure(ctx, req.(*GetSeriesStructureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_SearchContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).SearchContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_SearchContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).SearchContent(ctx, req.(*SearchContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListGenres_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGenresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListGenres(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListGenres_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListGenres(ctx, req.(*ListGenresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetPerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetPerson(ctx, req.(*GetPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_RateContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).RateContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_RateContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).RateContent(ctx, req.(*RateContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetUserRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetUserRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetUserRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetUserRating(ctx, req.(*GetUserRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateContent(ctx, req.(*CreateContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateContent(ctx, req.(*UpdateContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_PublishContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).PublishContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_PublishContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).PublishContent(ctx, req.(*PublishContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreatePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreatePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreatePerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreatePerson(ctx, req.(*CreatePersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_AddPersonToContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPersonToContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).AddPersonToContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_AddPersonToContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).AddPersonToContent(ctx, req.(*AddPersonToContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCatalog",
			Handler:    _CatalogService_GetCatalog_Handler,
		},
		{
			MethodName: "GetContentDetail",
			Handler:    _CatalogService_GetContentDetail_Handler,
		},
		{
			MethodName: "GetSeriesStructure",
			Handler:    _CatalogService_GetSeriesStructure_Handler,
		},
		{
			MethodName: "SearchContent",
			Handler:    _CatalogService_SearchContent_Handler,
		},
		{
			MethodName: "ListGenres",
			Handler:    _CatalogService_ListGenres_Handler,
		},
		{
			MethodName: "GetPerson",
			Handler:    _CatalogService_GetPerson_Handler,
		},
		{
			MethodName: "RateContent",
			Handler:    _CatalogService_RateContent_Handler,
		},
		{
			MethodName: "GetUserRating",
			Handler:    _CatalogService_GetUserRating_Handler,
		},
		{
			MethodName: "CreateContent",
			Handler:    _CatalogService_CreateContent_Handler,
		},
		{
			MethodName: "UpdateContent",
			Handler:    _CatalogService_UpdateContent_Handler,
		},
		{
			MethodName: "PublishContent",
			Handler:    _CatalogService_PublishContent_Handler,
		},
		{
			MethodName: "CreatePerson",
			Handler:    _CatalogService_CreatePerson_Handler,
		},
		{
			MethodName: "AddPersonToContent",
			Handler:    _CatalogService_AddPersonToContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog.proto",
}
