// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: fx.proto

package fx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExchangeRateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetCurrency string                 `protobuf:"bytes,1,opt,name=target_currency,json=targetCurrency,proto3" json:"target_currency,omitempty"`
	RequestedBy    string                 `protobuf:"bytes,2,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExchangeRateRequest) Reset() {
	*x = ExchangeRateRequest{}
	mi := &file_fx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateRequest) ProtoMessage() {}

func (x *ExchangeRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRateRequest) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeRateRequest) GetTargetCurrency() string {
	if x != nil {
		return x.TargetCurrency
	}
	return ""
}

func (x *ExchangeRateRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type AllRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestedBy   string                 `protobuf:"bytes,1,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllRatesRequest) Reset() {
	*x = AllRatesRequest{}
	mi := &file_fx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllRatesRequest) ProtoMessage() {}

func (x *AllRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllRatesRequest.ProtoReflect.Descriptor instead.
func (*AllRatesRequest) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{1}
}

func (x *AllRatesRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type ConvertAmountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Amount         float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	TargetCurrency string                 `protobuf:"bytes,2,opt,name=target_currency,json=targetCurrency,proto3" json:"target_currency,omitempty"`
	RequestedBy    string                 `protobuf:"bytes,3,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConvertAmountRequest) Reset() {
	*x = ConvertAmountRequest{}
	mi := &file_fx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertAmountRequest) ProtoMessage() {}

func (x *ConvertAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertAmountRequest.ProtoReflect.Descriptor instead.
func (*ConvertAmountRequest) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{2}
}

func (x *ConvertAmountRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConvertAmountRequest) GetTargetCurrency() string {
	if x != nil {
		return x.TargetCurrency
	}
	return ""
}

func (x *ConvertAmountRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type ExchangeRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyCode  string                 `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	CurrencyName  string                 `protobuf:"bytes,2,opt,name=currency_name,json=currencyName,proto3" json:"currency_name,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Rate          float64                `protobuf:"fixed64,4,opt,name=rate,proto3" json:"rate,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	ValidAt       string                 `protobuf:"bytes,6,opt,name=valid_at,json=validAt,proto3" json:"valid_at,omitempty"`
	Success       bool                   `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRateResponse) Reset() {
	*x = ExchangeRateResponse{}
	mi := &file_fx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateResponse) ProtoMessage() {}

func (x *ExchangeRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateResponse.ProtoReflect.Descriptor instead.
func (*ExchangeRateResponse) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeRateResponse) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *ExchangeRateResponse) GetCurrencyName() string {
	if x != nil {
		return x.CurrencyName
	}
	return ""
}

func (x *ExchangeRateResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ExchangeRateResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ExchangeRateResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ExchangeRateResponse) GetValidAt() string {
	if x != nil {
		return x.ValidAt
	}
	return ""
}

func (x *ExchangeRateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExchangeRateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RateItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyCode  string                 `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	CurrencyName  string                 `protobuf:"bytes,2,opt,name=currency_name,json=currencyName,proto3" json:"currency_name,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Rate          float64                `protobuf:"fixed64,4,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateItem) Reset() {
	*x = RateItem{}
	mi := &file_fx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateItem) ProtoMessage() {}

func (x *RateItem) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateItem.ProtoReflect.Descriptor instead.
func (*RateItem) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{4}
}

func (x *RateItem) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *RateItem) GetCurrencyName() string {
	if x != nil {
		return x.CurrencyName
	}
	return ""
}

func (x *RateItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RateItem) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type AllRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         []*RateItem            `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllRatesResponse) Reset() {
	*x = AllRatesResponse{}
	mi := &file_fx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllRatesResponse) ProtoMessage() {}

func (x *AllRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllRatesResponse.ProtoReflect.Descriptor instead.
func (*AllRatesResponse) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{5}
}

func (x *AllRatesResponse) GetRates() []*RateItem {
	if x != nil {
		return x.Rates
	}
	return nil
}

func (x *AllRatesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AllRatesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ConvertAmountResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OriginalAmount  float64                `protobuf:"fixed64,1,opt,name=original_amount,json=originalAmount,proto3" json:"original_amount,omitempty"`
	ConvertedAmount float64                `protobuf:"fixed64,2,opt,name=converted_amount,json=convertedAmount,proto3" json:"converted_amount,omitempty"`
	CurrencyCode    string                 `protobuf:"bytes,3,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Symbol          string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Rate            float64                `protobuf:"fixed64,5,opt,name=rate,proto3" json:"rate,omitempty"`
	Success         bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConvertAmountResponse) Reset() {
	*x = ConvertAmountResponse{}
	mi := &file_fx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertAmountResponse) ProtoMessage() {}

func (x *ConvertAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertAmountResponse.ProtoReflect.Descriptor instead.
func (*ConvertAmountResponse) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{6}
}

func (x *ConvertAmountResponse) GetOriginalAmount() float64 {
	if x != nil {
		return x.OriginalAmount
	}
	return 0
}

func (x *ConvertAmountResponse) GetConvertedAmount() float64 {
	if x != nil {
		return x.ConvertedAmount
	}
	return 0
}

func (x *ConvertAmountResponse) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *ConvertAmountResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ConvertAmountResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ConvertAmountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConvertAmountResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_fx_proto protoreflect.FileDescriptor

const file_fx_proto_rawDesc = "" +
	"\n" +
	"\bfx.proto\x12\x02fx\"a\n" +
	"\x13ExchangeRateRequest\x12'\n" +
	"\x0ftarget_currency\x18\x01 \x01(\tR\x0etargetCurrency\x12!\n" +
	"\frequested_by\x18\x02 \x01(\tR\vrequestedBy\"4\n" +
	"\x0fAllRatesRequest\x12!\n" +
	"\frequested_by\x18\x01 \x01(\tR\vrequestedBy\"z\n" +
	"\x14ConvertAmountRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12'\n" +
	"\x0ftarget_currency\x18\x02 \x01(\tR\x0etargetCurrency\x12!\n" +
	"\frequested_by\x18\x03 \x01(\tR\vrequestedBy\"\xfe\x01\n" +
	"\x14ExchangeRateResponse\x12#\n" +
	"\rcurrency_code\x18\x01 \x01(\tR\fcurrencyCode\x12#\n" +
	"\rcurrency_name\x18\x02 \x01(\tR\fcurrencyName\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04rate\x18\x04 \x01(\x01R\x04rate\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x19\n" +
	"\bvalid_at\x18\x06 \x01(\tR\avalidAt\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"\x80\x01\n" +
	"\bRateItem\x12#\n" +
	"\rcurrency_code\x18\x01 \x01(\tR\fcurrencyCode\x12#\n" +
	"\rcurrency_name\x18\x02 \x01(\tR\fcurrencyName\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04rate\x18\x04 \x01(\x01R\x04rate\"u\n" +
	"\x10AllRatesResponse\x12\"\n" +
	"\x05rates\x18\x01 \x03(\v2\f.fx.RateItemR\x05rates\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xfb\x01\n" +
	"\x15ConvertAmountResponse\x12'\n" +
	"\x0foriginal_amount\x18\x01 \x01(\x01R\x0eoriginalAmount\x12)\n" +
	"\x10converted_amount\x18\x02 \x01(\x01R\x0fconvertedAmount\x12#\n" +
	"\rcurrency_code\x18\x03 \x01(\tR\fcurrencyCode\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04rate\x18\x05 \x01(\x01R\x04rate\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage2\xd1\x01\n" +
	"\tFxService\x12D\n" +
	"\x0fGetExchangeRate\x12\x17.fx.ExchangeRateRequest\x1a\x18.fx.ExchangeRateResponse\x128\n" +
	"\vGetAllRates\x12\x13.fx.AllRatesRequest\x1a\x14.fx.AllRatesResponse\x12D\n" +
	"\rConvertAmount\x12\x18.fx.ConvertAmountRequest\x1a\x19.fx.ConvertAmountResponseB\"Z subscription-service/proto/fx;fxb\x06proto3"

var (
	file_fx_proto_rawDescOnce sync.Once
	file_fx_proto_rawDescData []byte
)

func file_fx_proto_rawDescGZIP() []byte {
	file_fx_proto_rawDescOnce.Do(func() {
		file_fx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fx_proto_rawDesc), len(file_fx_proto_rawDesc)))
	})
	return file_fx_proto_rawDescData
}

var file_fx_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_fx_proto_goTypes = []any{
	(*ExchangeRateRequest)(nil),   // 0: fx.ExchangeRateRequest
	(*AllRatesRequest)(nil),       // 1: fx.AllRatesRequest
	(*ConvertAmountRequest)(nil),  // 2: fx.ConvertAmountRequest
	(*ExchangeRateResponse)(nil),  // 3: fx.ExchangeRateResponse
	(*RateItem)(nil),              // 4: fx.RateItem
	(*AllRatesResponse)(nil),      // 5: fx.AllRatesResponse
	(*ConvertAmountResponse)(nil), // 6: fx.ConvertAmountResponse
}
var file_fx_proto_depIdxs = []int32{
	4, // 0: fx.AllRatesResponse.rates:type_name -> fx.RateItem
	0, // 1: fx.FxService.GetExchangeRate:input_type -> fx.ExchangeRateRequest
	1, // 2: fx.FxService.GetAllRates:input_type -> fx.AllRatesRequest
	2, // 3: fx.FxService.ConvertAmount:input_type -> fx.ConvertAmountRequest
	3, // 4: fx.FxService.GetExchangeRate:output_type -> fx.ExchangeRateResponse
	5, // 5: fx.FxService.GetAllRates:output_type -> fx.AllRatesResponse
	6, // 6: fx.FxService.ConvertAmount:output_type -> fx.ConvertAmountResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fx_proto_init() }
func file_fx_proto_init() {
	if File_fx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fx_proto_rawDesc), len(file_fx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fx_proto_goTypes,
		DependencyIndexes: file_fx_proto_depIdxs,
		MessageInfos:      file_fx_proto_msgTypes,
	}.Build()
	File_fx_proto = out.File
	file_fx_proto_goTypes = nil
	file_fx_proto_depIdxs = nil
}
