// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/subscription/subscription.proto

package subscription

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceUsd      float64                `protobuf:"fixed64,4,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`
	MaxProfiles   int32                  `protobuf:"varint,5,opt,name=max_profiles,json=maxProfiles,proto3" json:"max_profiles,omitempty"`
	MaxStreams    int32                  `protobuf:"varint,6,opt,name=max_streams,json=maxStreams,proto3" json:"max_streams,omitempty"`
	VideoQuality  string                 `protobuf:"bytes,7,opt,name=video_quality,json=videoQuality,proto3" json:"video_quality,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *Plan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Plan) GetPriceUsd() float64 {
	if x != nil {
		return x.PriceUsd
	}
	return 0
}

func (x *Plan) GetMaxProfiles() int32 {
	if x != nil {
		return x.MaxProfiles
	}
	return 0
}

func (x *Plan) GetMaxStreams() int32 {
	if x != nil {
		return x.MaxStreams
	}
	return 0
}

func (x *Plan) GetVideoQuality() string {
	if x != nil {
		return x.VideoQuality
	}
	return ""
}

func (x *Plan) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type PlanWithRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *Plan                  `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	LocalPrice    float64                `protobuf:"fixed64,2,opt,name=local_price,json=localPrice,proto3" json:"local_price,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	ExchangeRate  float64                `protobuf:"fixed64,4,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanWithRate) Reset() {
	*x = PlanWithRate{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanWithRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanWithRate) ProtoMessage() {}

func (x *PlanWithRate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanWithRate.ProtoReflect.Descriptor instead.
func (*PlanWithRate) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *PlanWithRate) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *PlanWithRate) GetLocalPrice() float64 {
	if x != nil {
		return x.LocalPrice
	}
	return 0
}

func (x *PlanWithRate) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PlanWithRate) GetExchangeRate() float64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

type GetPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlansRequest) Reset() {
	*x = GetPlansRequest{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlansRequest) ProtoMessage() {}

func (x *GetPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlansRequest.ProtoReflect.Descriptor instead.
func (*GetPlansRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{2}
}

type GetPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*Plan                `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlansResponse) Reset() {
	*x = GetPlansResponse{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlansResponse) ProtoMessage() {}

func (x *GetPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlansResponse.ProtoReflect.Descriptor instead.
func (*GetPlansResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlansResponse) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

type GetPlanByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanByIdRequest) Reset() {
	*x = GetPlanByIdRequest{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanByIdRequest) ProtoMessage() {}

func (x *GetPlanByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPlanByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlanByIdRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type GetPlansWithRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlansWithRatesRequest) Reset() {
	*x = GetPlansWithRatesRequest{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlansWithRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlansWithRatesRequest) ProtoMessage() {}

func (x *GetPlansWithRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlansWithRatesRequest.ProtoReflect.Descriptor instead.
func (*GetPlansWithRatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlansWithRatesRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetPlansWithRatesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPlansWithRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*PlanWithRate        `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlansWithRatesResponse) Reset() {
	*x = GetPlansWithRatesResponse{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlansWithRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlansWithRatesResponse) ProtoMessage() {}

func (x *GetPlansWithRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlansWithRatesResponse.ProtoReflect.Descriptor instead.
func (*GetPlansWithRatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *GetPlansWithRatesResponse) GetPlans() []*PlanWithRate {
	if x != nil {
		return x.Plans
	}
	return nil
}

func (x *GetPlansWithRatesResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	UserEmail     string                 `protobuf:"bytes,5,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubscribeRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *SubscribeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SubscribeRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *SubscribeRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type SubscribeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	PaymentId      string                 `protobuf:"bytes,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubscribeResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *SubscribeResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *SubscribeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{9}
}

func (x *CancelSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelSubscriptionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionResponse) Reset() {
	*x = CancelSubscriptionResponse{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionResponse) ProtoMessage() {}

func (x *CancelSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{10}
}

func (x *CancelSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelSubscriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSubscriptionRequest) Reset() {
	*x = GetUserSubscriptionRequest{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubscriptionRequest) ProtoMessage() {}

func (x *GetUserSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetUserSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserSubscriptionResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	HasActiveSubscription bool                   `protobuf:"varint,1,opt,name=has_active_subscription,json=hasActiveSubscription,proto3" json:"has_active_subscription,omitempty"`
	SubscriptionId        string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	PlanId                string                 `protobuf:"bytes,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	PlanName              string                 `protobuf:"bytes,4,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	PlanPriceUsd          float64                `protobuf:"fixed64,5,opt,name=plan_price_usd,json=planPriceUsd,proto3" json:"plan_price_usd,omitempty"`
	Status                string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	StartDate             string                 `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	RenewalDate           string                 `protobuf:"bytes,8,opt,name=renewal_date,json=renewalDate,proto3" json:"renewal_date,omitempty"`
	DaysRemaining         int32                  `protobuf:"varint,9,opt,name=days_remaining,json=daysRemaining,proto3" json:"days_remaining,omitempty"`
	MaxProfiles           int32                  `protobuf:"varint,10,opt,name=max_profiles,json=maxProfiles,proto3" json:"max_profiles,omitempty"`
	MaxStreams            int32                  `protobuf:"varint,11,opt,name=max_streams,json=maxStreams,proto3" json:"max_streams,omitempty"`
	VideoQuality          string                 `protobuf:"bytes,12,opt,name=video_quality,json=videoQuality,proto3" json:"video_quality,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserSubscriptionResponse) Reset() {
	*x = UserSubscriptionResponse{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSubscriptionResponse) ProtoMessage() {}

func (x *UserSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*UserSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{12}
}

func (x *UserSubscriptionResponse) GetHasActiveSubscription() bool {
	if x != nil {
		return x.HasActiveSubscription
	}
	return false
}

func (x *UserSubscriptionResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *UserSubscriptionResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *UserSubscriptionResponse) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *UserSubscriptionResponse) GetPlanPriceUsd() float64 {
	if x != nil {
		return x.PlanPriceUsd
	}
	return 0
}

func (x *UserSubscriptionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserSubscriptionResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UserSubscriptionResponse) GetRenewalDate() string {
	if x != nil {
		return x.RenewalDate
	}
	return ""
}

func (x *UserSubscriptionResponse) GetDaysRemaining() int32 {
	if x != nil {
		return x.DaysRemaining
	}
	return 0
}

func (x *UserSubscriptionResponse) GetMaxProfiles() int32 {
	if x != nil {
		return x.MaxProfiles
	}
	return 0
}

func (x *UserSubscriptionResponse) GetMaxStreams() int32 {
	if x != nil {
		return x.MaxStreams
	}
	return 0
}

func (x *UserSubscriptionResponse) GetVideoQuality() string {
	if x != nil {
		return x.VideoQuality
	}
	return ""
}

type Payment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	PlanName       string                 `protobuf:"bytes,3,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	AmountUsd      float64                `protobuf:"fixed64,4,opt,name=amount_usd,json=amountUsd,proto3" json:"amount_usd,omitempty"`
	AmountLocal    float64                `protobuf:"fixed64,5,opt,name=amount_local,json=amountLocal,proto3" json:"amount_local,omitempty"`
	Currency       string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	ExchangeRate   float64                `protobuf:"fixed64,7,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	PaymentMethod  string                 `protobuf:"bytes,9,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TransactionRef string                 `protobuf:"bytes,10,opt,name=transaction_ref,json=transactionRef,proto3" json:"transaction_ref,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{13}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Payment) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *Payment) GetAmountUsd() float64 {
	if x != nil {
		return x.AmountUsd
	}
	return 0
}

func (x *Payment) GetAmountLocal() float64 {
	if x != nil {
		return x.AmountLocal
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetExchangeRate() float64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Payment) GetTransactionRef() string {
	if x != nil {
		return x.TransactionRef
	}
	return ""
}

func (x *Payment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetPaymentHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentHistoryRequest) Reset() {
	*x = GetPaymentHistoryRequest{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentHistoryRequest) ProtoMessage() {}

func (x *GetPaymentHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{14}
}

func (x *GetPaymentHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPaymentHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPaymentHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetPaymentHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentHistoryResponse) Reset() {
	*x = GetPaymentHistoryResponse{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentHistoryResponse) ProtoMessage() {}

func (x *GetPaymentHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{15}
}

func (x *GetPaymentHistoryResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *GetPaymentHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Una entrada de la tabla audit_log poblada por los triggers de la BD.
type AuditLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TableName     string                 `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"` // tabla afectada: plans | subscriptions | payments
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`                  // INSERT | UPDATE | DELETE
	ChangedBy     string                 `protobuf:"bytes,4,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"` // usuario responsable
	ChangedAt     string                 `protobuf:"bytes,5,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"` // timestamp ISO 8601
	OldData       string                 `protobuf:"bytes,6,opt,name=old_data,json=oldData,proto3" json:"old_data,omitempty"`       // snapshot anterior (JSON serializado)
	NewData       string                 `protobuf:"bytes,7,opt,name=new_data,json=newData,proto3" json:"new_data,omitempty"`       // snapshot nuevo (JSON serializado)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogEntry) Reset() {
	*x = AuditLogEntry{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEntry) ProtoMessage() {}

func (x *AuditLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEntry.ProtoReflect.Descriptor instead.
func (*AuditLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{16}
}

func (x *AuditLogEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditLogEntry) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *AuditLogEntry) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *AuditLogEntry) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *AuditLogEntry) GetChangedAt() string {
	if x != nil {
		return x.ChangedAt
	}
	return ""
}

func (x *AuditLogEntry) GetOldData() string {
	if x != nil {
		return x.OldData
	}
	return ""
}

func (x *AuditLogEntry) GetNewData() string {
	if x != nil {
		return x.NewData
	}
	return ""
}

type GetAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"` // filtro opcional por tabla
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`                  // filtro opcional por operación
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`                            // filtro opcional desde (ISO 8601)
	To            string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`                                // filtro opcional hasta (ISO 8601)
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogsRequest) Reset() {
	*x = GetAuditLogsRequest{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogsRequest) ProtoMessage() {}

func (x *GetAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{17}
}

func (x *GetAuditLogsRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *GetAuditLogsRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *GetAuditLogsRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetAuditLogsRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *GetAuditLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAuditLogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditLogEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogsResponse) Reset() {
	*x = GetAuditLogsResponse{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogsResponse) ProtoMessage() {}

func (x *GetAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*GetAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{18}
}

func (x *GetAuditLogsResponse) GetEntries() []*AuditLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetAuditLogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAuditLogsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAuditLogsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ExportAuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"` // "csv" | "pdf"
	TableName     string                 `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAuditLogRequest) Reset() {
	*x = ExportAuditLogRequest{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAuditLogRequest) ProtoMessage() {}

func (x *ExportAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAuditLogRequest.ProtoReflect.Descriptor instead.
func (*ExportAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{19}
}

func (x *ExportAuditLogRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ExportAuditLogRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ExportAuditLogRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ExportAuditLogRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ExportAuditLogRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type ExportAuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                            // archivo generado
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // text/csv | application/pdf
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`                          // nombre sugerido de descarga
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAuditLogResponse) Reset() {
	*x = ExportAuditLogResponse{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAuditLogResponse) ProtoMessage() {}

func (x *ExportAuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAuditLogResponse.ProtoReflect.Descriptor instead.
func (*ExportAuditLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{20}
}

func (x *ExportAuditLogResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ExportAuditLogResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExportAuditLogResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_proto_subscription_subscription_proto protoreflect.FileDescriptor

const file_proto_subscription_subscription_proto_rawDesc = "" +
	"\n" +
	"%proto/subscription/subscription.proto\x12\fsubscription\"\xef\x01\n" +
	"\x04Plan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tprice_usd\x18\x04 \x01(\x01R\bpriceUsd\x12!\n" +
	"\fmax_profiles\x18\x05 \x01(\x05R\vmaxProfiles\x12\x1f\n" +
	"\vmax_streams\x18\x06 \x01(\x05R\n" +
	"maxStreams\x12#\n" +
	"\rvideo_quality\x18\a \x01(\tR\fvideoQuality\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\"\x98\x01\n" +
	"\fPlanWithRate\x12&\n" +
	"\x04plan\x18\x01 \x01(\v2\x12.subscription.PlanR\x04plan\x12\x1f\n" +
	"\vlocal_price\x18\x02 \x01(\x01R\n" +
	"localPrice\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12#\n" +
	"\rexchange_rate\x18\x04 \x01(\x01R\fexchangeRate\"\x11\n" +
	"\x0fGetPlansRequest\"<\n" +
	"\x10GetPlansResponse\x12(\n" +
	"\x05plans\x18\x01 \x03(\v2\x12.subscription.PlanR\x05plans\"-\n" +
	"\x12GetPlanByIdRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\"O\n" +
	"\x18GetPlansWithRatesRequest\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"i\n" +
	"\x19GetPlansWithRatesResponse\x120\n" +
	"\x05plans\x18\x01 \x03(\v2\x1a.subscription.PlanWithRateR\x05plans\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xa6\x01\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x1d\n" +
	"\n" +
	"user_email\x18\x05 \x01(\tR\tuserEmail\"\x8f\x01\n" +
	"\x11SubscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x03 \x01(\tR\tpaymentId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"L\n" +
	"\x19CancelSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"P\n" +
	"\x1aCancelSubscriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x1aGetUserSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xc1\x03\n" +
	"\x18UserSubscriptionResponse\x126\n" +
	"\x17has_active_subscription\x18\x01 \x01(\bR\x15hasActiveSubscription\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12\x17\n" +
	"\aplan_id\x18\x03 \x01(\tR\x06planId\x12\x1b\n" +
	"\tplan_name\x18\x04 \x01(\tR\bplanName\x12$\n" +
	"\x0eplan_price_usd\x18\x05 \x01(\x01R\fplanPriceUsd\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_date\x18\a \x01(\tR\tstartDate\x12!\n" +
	"\frenewal_date\x18\b \x01(\tR\vrenewalDate\x12%\n" +
	"\x0edays_remaining\x18\t \x01(\x05R\rdaysRemaining\x12!\n" +
	"\fmax_profiles\x18\n" +
	" \x01(\x05R\vmaxProfiles\x12\x1f\n" +
	"\vmax_streams\x18\v \x01(\x05R\n" +
	"maxStreams\x12#\n" +
	"\rvideo_quality\x18\f \x01(\tR\fvideoQuality\"\xe9\x02\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12\x1b\n" +
	"\tplan_name\x18\x03 \x01(\tR\bplanName\x12\x1d\n" +
	"\n" +
	"amount_usd\x18\x04 \x01(\x01R\tamountUsd\x12!\n" +
	"\famount_local\x18\x05 \x01(\x01R\vamountLocal\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12#\n" +
	"\rexchange_rate\x18\a \x01(\x01R\fexchangeRate\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12%\n" +
	"\x0epayment_method\x18\t \x01(\tR\rpaymentMethod\x12'\n" +
	"\x0ftransaction_ref\x18\n" +
	" \x01(\tR\x0etransactionRef\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"a\n" +
	"\x18GetPaymentHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"d\n" +
	"\x19GetPaymentHistoryResponse\x121\n" +
	"\bpayments\x18\x01 \x03(\v2\x15.subscription.PaymentR\bpayments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xd0\x01\n" +
	"\rAuditLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x1d\n" +
	"\n" +
	"changed_by\x18\x04 \x01(\tR\tchangedBy\x12\x1d\n" +
	"\n" +
	"changed_at\x18\x05 \x01(\tR\tchangedAt\x12\x19\n" +
	"\bold_data\x18\x06 \x01(\tR\aoldData\x12\x19\n" +
	"\bnew_data\x18\a \x01(\tR\anewData\"\xa7\x01\n" +
	"\x13GetAuditLogsRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\x94\x01\n" +
	"\x14GetAuditLogsResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.subscription.AuditLogEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x90\x01\n" +
	"\x15ExportAuditLogRequest\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\tR\x02to\"q\n" +
	"\x16ExportAuditLogResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename2\xc5\x06\n" +
	"\x13SubscriptionService\x12I\n" +
	"\bGetPlans\x12\x1d.subscription.GetPlansRequest\x1a\x1e.subscription.GetPlansResponse\x12C\n" +
	"\vGetPlanById\x12 .subscription.GetPlanByIdRequest\x1a\x12.subscription.Plan\x12d\n" +
	"\x11GetPlansWithRates\x12&.subscription.GetPlansWithRatesRequest\x1a'.subscription.GetPlansWithRatesResponse\x12L\n" +
	"\tSubscribe\x12\x1e.subscription.SubscribeRequest\x1a\x1f.subscription.SubscribeResponse\x12g\n" +
	"\x12CancelSubscription\x12'.subscription.CancelSubscriptionRequest\x1a(.subscription.CancelSubscriptionResponse\x12g\n" +
	"\x13GetUserSubscription\x12(.subscription.GetUserSubscriptionRequest\x1a&.subscription.UserSubscriptionResponse\x12d\n" +
	"\x11GetPaymentHistory\x12&.subscription.GetPaymentHistoryRequest\x1a'.subscription.GetPaymentHistoryResponse\x12U\n" +
	"\fGetAuditLogs\x12!.subscription.GetAuditLogsRequest\x1a\".subscription.GetAuditLogsResponse\x12[\n" +
	"\x0eExportAuditLog\x12#.subscription.ExportAuditLogRequest\x1a$.subscription.ExportAuditLogResponseB6Z4subscription-service/proto/subscription;subscriptionb\x06proto3"

var (
	file_proto_subscription_subscription_proto_rawDescOnce sync.Once
	file_proto_subscription_subscription_proto_rawDescData []byte
)

func file_proto_subscription_subscription_proto_rawDescGZIP() []byte {
	file_proto_subscription_subscription_proto_rawDescOnce.Do(func() {
		file_proto_subscription_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subscription_subscription_proto_rawDesc), len(file_proto_subscription_subscription_proto_rawDesc)))
	})
	return file_proto_subscription_subscription_proto_rawDescData
}

var file_proto_subscription_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_subscription_subscription_proto_goTypes = []any{
	(*Plan)(nil),                       // 0: subscription.Plan
	(*PlanWithRate)(nil),               // 1: subscription.PlanWithRate
	(*GetPlansRequest)(nil),            // 2: subscription.GetPlansRequest
	(*GetPlansResponse)(nil),           // 3: subscription.GetPlansResponse
	(*GetPlanByIdRequest)(nil),         // 4: subscription.GetPlanByIdRequest
	(*GetPlansWithRatesRequest)(nil),   // 5: subscription.GetPlansWithRatesRequest
	(*GetPlansWithRatesResponse)(nil),  // 6: subscription.GetPlansWithRatesResponse
	(*SubscribeRequest)(nil),           // 7: subscription.SubscribeRequest
	(*SubscribeResponse)(nil),          // 8: subscription.SubscribeResponse
	(*CancelSubscriptionRequest)(nil),  // 9: subscription.CancelSubscriptionRequest
	(*CancelSubscriptionResponse)(nil), // 10: subscription.CancelSubscriptionResponse
	(*GetUserSubscriptionRequest)(nil), // 11: subscription.GetUserSubscriptionRequest
	(*UserSubscriptionResponse)(nil),   // 12: subscription.UserSubscriptionResponse
	(*Payment)(nil),                    // 13: subscription.Payment
	(*GetPaymentHistoryRequest)(nil),   // 14: subscription.GetPaymentHistoryRequest
	(*GetPaymentHistoryResponse)(nil),  // 15: subscription.GetPaymentHistoryResponse
	(*AuditLogEntry)(nil),              // 16: subscription.AuditLogEntry
	(*GetAuditLogsRequest)(nil),        // 17: subscription.GetAuditLogsRequest
	(*GetAuditLogsResponse)(nil),       // 18: subscription.GetAuditLogsResponse
	(*ExportAuditLogRequest)(nil),      // 19: subscription.ExportAuditLogRequest
	(*ExportAuditLogResponse)(nil),     // 20: subscription.ExportAuditLogResponse
}
var file_proto_subscription_subscription_proto_depIdxs = []int32{
	0,  // 0: subscription.PlanWithRate.plan:type_name -> subscription.Plan
	0,  // 1: subscription.GetPlansResponse.plans:type_name -> subscription.Plan
	1,  // 2: subscription.GetPlansWithRatesResponse.plans:type_name -> subscription.PlanWithRate
	13, // 3: subscription.GetPaymentHistoryResponse.payments:type_name -> subscription.Payment
	16, // 4: subscription.GetAuditLogsResponse.entries:type_name -> subscription.AuditLogEntry
	2,  // 5: subscription.SubscriptionService.GetPlans:input_type -> subscription.GetPlansRequest
	4,  // 6: subscription.SubscriptionService.GetPlanById:input_type -> subscription.GetPlanByIdRequest
	5,  // 7: subscription.SubscriptionService.GetPlansWithRates:input_type -> subscription.GetPlansWithRatesRequest
	7,  // 8: subscription.SubscriptionService.Subscribe:input_type -> subscription.SubscribeRequest
	9,  // 9: subscription.SubscriptionService.CancelSubscription:input_type -> subscription.CancelSubscriptionRequest
	11, // 10: subscription.SubscriptionService.GetUserSubscription:input_type -> subscription.GetUserSubscriptionRequest
	14, // 11: subscription.SubscriptionService.GetPaymentHistory:input_type -> subscription.GetPaymentHistoryRequest
	17, // 12: subscription.SubscriptionService.GetAuditLogs:input_type -> subscription.GetAuditLogsRequest
	19, // 13: subscription.SubscriptionService.ExportAuditLog:input_type -> subscription.ExportAuditLogRequest
	3,  // 14: subscription.SubscriptionService.GetPlans:output_type -> subscription.GetPlansResponse
	0,  // 15: subscription.SubscriptionService.GetPlanById:output_type -> subscription.Plan
	6,  // 16: subscription.SubscriptionService.GetPlansWithRates:output_type -> subscription.GetPlansWithRatesResponse
	8,  // 17: subscription.SubscriptionService.Subscribe:output_type -> subscription.SubscribeResponse
	10, // 18: subscription.SubscriptionService.CancelSubscription:output_type -> subscription.CancelSubscriptionResponse
	12, // 19: subscription.SubscriptionService.GetUserSubscription:output_type -> subscription.UserSubscriptionResponse
	15, // 20: subscription.SubscriptionService.GetPaymentHistory:output_type -> subscription.GetPaymentHistoryResponse
	18, // 21: subscription.SubscriptionService.GetAuditLogs:output_type -> subscription.GetAuditLogsResponse
	20, // 22: subscription.SubscriptionService.ExportAuditLog:output_type -> subscription.ExportAuditLogResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_subscription_subscription_proto_init() }
func file_proto_subscription_subscription_proto_init() {
	if File_proto_subscription_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subscription_subscription_proto_rawDesc), len(file_proto_subscription_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_subscription_subscription_proto_goTypes,
		DependencyIndexes: file_proto_subscription_subscription_proto_depIdxs,
		MessageInfos:      file_proto_subscription_subscription_proto_msgTypes,
	}.Build()
	File_proto_subscription_subscription_proto = out.File
	file_proto_subscription_subscription_proto_goTypes = nil
	file_proto_subscription_subscription_proto_depIdxs = nil
}
