apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: quetxal-tv-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ${ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${ARTIFACT_REGISTRY_REPOSITORY}/api-gateway:${IMAGE_TAG}
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "75m"
              memory: "192Mi"
            limits:
              cpu: "300m"
              memory: "384Mi"
          envFrom:
            - configMapRef:
                name: quetxal-tv-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: quetxal-tv-secrets
                  key: JWT_SECRET
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: quetxal-tv-secrets
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: quetxal-tv-secrets
                  key: JWT_REFRESH_SECRET
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 90
            periodSeconds: 20
            failureThreshold: 3
