# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import historial_pb2 as historial__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in historial_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class HistorialServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GuardarProgreso = channel.unary_unary(
                '/historial.HistorialService/GuardarProgreso',
                request_serializer=historial__pb2.GuardarProgresoRequest.SerializeToString,
                response_deserializer=historial__pb2.GuardarProgresoResponse.FromString,
                _registered_method=True)
        self.ObtenerContinuarViendo = channel.unary_unary(
                '/historial.HistorialService/ObtenerContinuarViendo',
                request_serializer=historial__pb2.ContinuarViendoRequest.SerializeToString,
                response_deserializer=historial__pb2.ContinuarViendoResponse.FromString,
                _registered_method=True)
        self.ObtenerHistorialPorPerfil = channel.unary_unary(
                '/historial.HistorialService/ObtenerHistorialPorPerfil',
                request_serializer=historial__pb2.HistorialPorPerfilRequest.SerializeToString,
                response_deserializer=historial__pb2.HistorialPorPerfilResponse.FromString,
                _registered_method=True)


class HistorialServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GuardarProgreso(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerContinuarViendo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerHistorialPorPerfil(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HistorialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GuardarProgreso': grpc.unary_unary_rpc_method_handler(
                    servicer.GuardarProgreso,
                    request_deserializer=historial__pb2.GuardarProgresoRequest.FromString,
                    response_serializer=historial__pb2.GuardarProgresoResponse.SerializeToString,
            ),
            'ObtenerContinuarViendo': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerContinuarViendo,
                    request_deserializer=historial__pb2.ContinuarViendoRequest.FromString,
                    response_serializer=historial__pb2.ContinuarViendoResponse.SerializeToString,
            ),
            'ObtenerHistorialPorPerfil': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerHistorialPorPerfil,
                    request_deserializer=historial__pb2.HistorialPorPerfilRequest.FromString,
                    response_serializer=historial__pb2.HistorialPorPerfilResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'historial.HistorialService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('historial.HistorialService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HistorialService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GuardarProgreso(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/historial.HistorialService/GuardarProgreso',
            historial__pb2.GuardarProgresoRequest.SerializeToString,
            historial__pb2.GuardarProgresoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerContinuarViendo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/historial.HistorialService/ObtenerContinuarViendo',
            historial__pb2.ContinuarViendoRequest.SerializeToString,
            historial__pb2.ContinuarViendoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerHistorialPorPerfil(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/historial.HistorialService/ObtenerHistorialPorPerfil',
            historial__pb2.HistorialPorPerfilRequest.SerializeToString,
            historial__pb2.HistorialPorPerfilResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
