# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import historial_pb2 as historial__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in historial_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HistorialServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateMovieProgress = channel.unary_unary(
                '/historial.HistorialService/UpdateMovieProgress',
                request_serializer=historial__pb2.UpdateMovieProgressRequest.SerializeToString,
                response_deserializer=historial__pb2.ProgressResponse.FromString,
                _registered_method=True)
        self.UpdateEpisodeProgress = channel.unary_unary(
                '/historial.HistorialService/UpdateEpisodeProgress',
                request_serializer=historial__pb2.UpdateEpisodeProgressRequest.SerializeToString,
                response_deserializer=historial__pb2.ProgressResponse.FromString,
                _registered_method=True)
        self.GetContinueWatching = channel.unary_unary(
                '/historial.HistorialService/GetContinueWatching',
                request_serializer=historial__pb2.GetContinueWatchingRequest.SerializeToString,
                response_deserializer=historial__pb2.ContinueWatchingResponse.FromString,
                _registered_method=True)
        self.GetContentProgress = channel.unary_unary(
                '/historial.HistorialService/GetContentProgress',
                request_serializer=historial__pb2.GetContentProgressRequest.SerializeToString,
                response_deserializer=historial__pb2.ProgressResponse.FromString,
                _registered_method=True)


class HistorialServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def UpdateMovieProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEpisodeProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContinueWatching(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContentProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HistorialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateMovieProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMovieProgress,
                    request_deserializer=historial__pb2.UpdateMovieProgressRequest.FromString,
                    response_serializer=historial__pb2.ProgressResponse.SerializeToString,
            ),
            'UpdateEpisodeProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEpisodeProgress,
                    request_deserializer=historial__pb2.UpdateEpisodeProgressRequest.FromString,
                    response_serializer=historial__pb2.ProgressResponse.SerializeToString,
            ),
            'GetContinueWatching': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContinueWatching,
                    request_deserializer=historial__pb2.GetContinueWatchingRequest.FromString,
                    response_serializer=historial__pb2.ContinueWatchingResponse.SerializeToString,
            ),
            'GetContentProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContentProgress,
                    request_deserializer=historial__pb2.GetContentProgressRequest.FromString,
                    response_serializer=historial__pb2.ProgressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'historial.HistorialService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('historial.HistorialService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HistorialService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateMovieProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/historial.HistorialService/UpdateMovieProgress',
            historial__pb2.UpdateMovieProgressRequest.SerializeToString,
            historial__pb2.ProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEpisodeProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/historial.HistorialService/UpdateEpisodeProgress',
            historial__pb2.UpdateEpisodeProgressRequest.SerializeToString,
            historial__pb2.ProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContinueWatching(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/historial.HistorialService/GetContinueWatching',
            historial__pb2.GetContinueWatchingRequest.SerializeToString,
            historial__pb2.ContinueWatchingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContentProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/historial.HistorialService/GetContentProgress',
            historial__pb2.GetContentProgressRequest.SerializeToString,
            historial__pb2.ProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
