# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: historial.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fhistorial.proto\x12\thistorial\"\xda\x01\n\x16GuardarProgresoRequest\x12\x12\n\nprofile_id\x18\x01 \x01(\t\x12\x12\n\ncontent_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\x12\x16\n\x0eminute_reached\x18\x04 \x01(\x05\x12\x1a\n\x12total_duration_min\x18\x05 \x01(\x05\x12\x11\n\tseason_id\x18\x06 \x01(\t\x12\x12\n\nepisode_id\x18\x07 \x01(\t\x12\x12\n\nseason_num\x18\x08 \x01(\x05\x12\x13\n\x0b\x65pisode_num\x18\t \x01(\x05\";\n\x17GuardarProgresoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\";\n\x16\x43ontinuarViendoRequest\x12\x12\n\nprofile_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"/\n\x19HistorialPorPerfilRequest\x12\x12\n\nprofile_id\x18\x01 \x01(\t\"\xc0\x02\n\x0cProgresoItem\x12\x13\n\x0bprogress_id\x18\x01 \x01(\t\x12\x12\n\nprofile_id\x18\x02 \x01(\t\x12\x12\n\ncontent_id\x18\x03 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\t\x12\x16\n\x0eminute_reached\x18\x05 \x01(\x05\x12\x1a\n\x12total_duration_min\x18\x06 \x01(\x05\x12\x16\n\x0e\x63ompletion_pct\x18\x07 \x01(\x01\x12\x14\n\x0cis_completed\x18\x08 \x01(\x08\x12\x17\n\x0flast_watched_at\x18\t \x01(\t\x12\x17\n\x0flast_episode_id\x18\n \x01(\t\x12\x17\n\x0flast_season_num\x18\x0b \x01(\x05\x12\x18\n\x10last_episode_num\x18\x0c \x01(\x05\x12\x16\n\x0elast_ep_minute\x18\r \x01(\x05\"A\n\x17\x43ontinuarViendoResponse\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.historial.ProgresoItem\"D\n\x1aHistorialPorPerfilResponse\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.historial.ProgresoItem2\xb7\x02\n\x10HistorialService\x12X\n\x0fGuardarProgreso\x12!.historial.GuardarProgresoRequest\x1a\".historial.GuardarProgresoResponse\x12_\n\x16ObtenerContinuarViendo\x12!.historial.ContinuarViendoRequest\x1a\".historial.ContinuarViendoResponse\x12h\n\x19ObtenerHistorialPorPerfil\x12$.historial.HistorialPorPerfilRequest\x1a%.historial.HistorialPorPerfilResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'historial_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GUARDARPROGRESOREQUEST']._serialized_start=31
  _globals['_GUARDARPROGRESOREQUEST']._serialized_end=249
  _globals['_GUARDARPROGRESORESPONSE']._serialized_start=251
  _globals['_GUARDARPROGRESORESPONSE']._serialized_end=310
  _globals['_CONTINUARVIENDOREQUEST']._serialized_start=312
  _globals['_CONTINUARVIENDOREQUEST']._serialized_end=371
  _globals['_HISTORIALPORPERFILREQUEST']._serialized_start=373
  _globals['_HISTORIALPORPERFILREQUEST']._serialized_end=420
  _globals['_PROGRESOITEM']._serialized_start=423
  _globals['_PROGRESOITEM']._serialized_end=743
  _globals['_CONTINUARVIENDORESPONSE']._serialized_start=745
  _globals['_CONTINUARVIENDORESPONSE']._serialized_end=810
  _globals['_HISTORIALPORPERFILRESPONSE']._serialized_start=812
  _globals['_HISTORIALPORPERFILRESPONSE']._serialized_end=880
  _globals['_HISTORIALSERVICE']._serialized_start=883
  _globals['_HISTORIALSERVICE']._serialized_end=1194
# @@protoc_insertion_point(module_scope)
