apiVersion: v1
kind: Service
metadata: { name: historial-service, namespace: quetxal-tv-prod }
spec:
  type: ClusterIP
  selector: { app: historial-service }
  ports: [{ port: 50054, targetPort: 50054 }]
